kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}-deploy"
  namespace: "{{ .Release.Namespace }}"
  labels:
    deploy: "{{ .Release.Name }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      deploy: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        deploy: "{{ .Release.Name }}"
    spec:
      containers:
        - name: ara-api
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ARA_ALLOWED_HOSTS
              value: "{{ .Values.env.ARA_ALLOWED_HOSTS }}"
